### ISSUE TITLE
When visiting app: Incompatible character encodings: ASCII-8BIT and UTF-8

### ISSUE THREAD

**Issue by jmasukawa** [crewmate/crewmate#73]
Hi there, I have been using the vanilla teambox3 for some time and finally got around to migrating to crewmate (awesome work you guys!). Starting from a fresh database and bootstrapping it seems to work just fine, but using my existing database doesn't seem to work.

I followed the migration readme and ran the 'bundle exec rake db:migrate' command on my production environment.  The WEBrick server starts up fine, but when visiting the site i get the following error:

```
Encoding::CompatibilityError in Projects#index
Showing /var/www/crewmate/app/views/projects/index.haml where line #16 raised:

incompatible character encodings: ASCII-8BIT and UTF-8
Extracted source (around line #16):

13:     - form.object.comments.build
14:     - form.fields_for :comments do |fields|
15:       = render 'comments/fields', :f => fields, :placeholder => t('comments.new.project')
16: 
17: - if current_user.projects.any?
18:   #activities
19:     = list_threads(@threads)
Rails.root: /var/www/crewmate
```

Any ideas? I rewrote the problematic area by hand in vim like some SO posts suggested, but still not working. I have the full stack trace if that would be useful. Thanks!

**Comment by ganar** [comment]
Hello @jnv: I'm having the same issue. My content comes from Teambox 3, and other than the wrong encoding —garbled characters in the output— everything seems to be working fine
- I've added `encoding: utf8` to `config/database.yml`
- I've checked and rechecked the encoding and the data in the new database

Any pointer that you can give me regarding this?

**Comment by ganar** [comment]
Hello @jnv, @jmasukaw 

In my case, the solution was to edit the affected tables using the information on this article:

[How to fix double-encoded UTF8 characters (in an utf-8 table)](http://stackoverflow.com/questions/11436594/how-to-fix-double-encoded-utf8-characters-in-an-utf-8-table)

Here is an example of one of the many queries that had to be executed in order to solve the issue

`UPDATE comments SET body_html = CONVERT(CAST(CONVERT(body_html USING latin1) AS BINARY) USING utf8);`

There were many columns affected
